### ISSUE TITLE
Error stack trace should not include Zod internals

### ISSUE THREAD

**Issue by flybayer** [colinhacks/zod#101]
Currently the stack trace includes Zod internals like this:

```diff
ZodError: event.data.new.title: Invalid input: expected string, received undefined
-    at new ZodError (/Users/b/c/infra/node_modules/zod/lib/src/ZodError.js:36:28)
-    at ZodObject.parse (/Users/b/c/infra/node_modules/zod/lib/src/parser.js:142:17)
    at exports.handler (webpack-internal:///./functions/hasura/eventCreated.ts:41:39)
    at InProcessRunner.run (/Users/b/c/infra/node_modules/serverless-offline/dist/lambda/handler-runner/in-process-runner/InProcessRunner.js:100:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async process.<anonymous> (/Users/b/c/infra/node_modules/serverless-offline/dist/lambda/handler-runner/child-process-runner/childProcessHelper.js:39:14)
}
```

But what I want is this:
```
ZodError: event.data.new.title: Invalid input: expected string, received undefined
    at exports.handler (webpack-internal:///./functions/hasura/eventCreated.ts:41:39)
    at InProcessRunner.run (/Users/b/c/infra/node_modules/serverless-offline/dist/lambda/handler-runner/in-process-runner/InProcessRunner.js:100:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async process.<anonymous> (/Users/b/c/infra/node_modules/serverless-offline/dist/lambda/handler-runner/child-process-runner/childProcessHelper.js:39:14) 
}
```

#### Version

```
zod: 1.9.0
```

**Comment by vriad** [comment]
Open to a PR for this. TBH I don't know how to do this.
