### ISSUE TITLE
'Invalid binding pattern' error when remapping object properties in transformer

### ISSUE THREAD

**Issue by jcayzac** [colinhacks/zod#1270]
Using a spread operator in a transformer raises an error.

### Versions

* node v18.3.0
* zod v3.17.9
* typescript 4.7.4

### Repro

```ts
//  SymbolInfo.ts
import { z } from 'zod'

const Parser = z.object({
    business_description: z.string().min(1),
    country: z.string().min(1),
    currency_code: z.string().min(1),
    exchange: z.string().min(1),
    industry: z.string().min(1),
    isin: z.string().min(1),
    local_code: z.string().min(1),
    nsin: z.string().min(1),
    pro_name: z.string().min(1),
    sector: z.string().min(1),
    sedol: z.string().min(1),
    session_holidays: z.string()
      .refine((x) => /^(?:\d{8},?)*$/.test(x))
      .transform((x) => x.split(',')),
    short_description: z.string().min(1),
    web_site_url: z.string().min(1),
  })
  .transform(({
    business_description: description,
    currency_code: currency,
    pro_name: identifier,
    local_code: localCode,
    session_holidays: holidays,
    short_description: name,
    web_site_url: url,
    ...entries,
  }) => ({
    identifier,
    name,
    localCode,
    description,
    url,
    currency,
    holidays,
    ...entries,
  }))

export type SymbolInfo = z.infer<typeof Parser>
export const createSymbolInfo = (params: unknown): SymbolInfo => Parser.parse(params)
```

```json5
// tsconfig.json
{
  "compilerOptions": {
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "target": "esnext",
    "strict": true,
  },
}
```

### Error

```text
Error: Transform failed with 1 error:
file:///project/SymbolInfo.ts:29:14: ERROR: Invalid binding pattern
    at failureErrorWithLog (/project/node_modules/.pnpm/esbuild@0.14.48/node_modules/esbuild/lib/main.js:1605:15)
    at /project/node_modules/.pnpm/esbuild@0.14.48/node_modules/esbuild/lib/main.js:1394:29
    at /project/node_modules/.pnpm/esbuild@0.14.48/node_modules/esbuild/lib/main.js:666:9
    at handleIncomingPacket (/project/node_modules/.pnpm/esbuild@0.14.48/node_modules/esbuild/lib/main.js:763:9)
    at Socket.readFromStdout (/project/node_modules/.pnpm/esbuild@0.14.48/node_modules/esbuild/lib/main.js:632:7)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 14,
        file: 'file:///project/SymbolInfo.ts',
        length: 1,
        line: 29,
        lineText: '    ...entries,',
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'Invalid binding pattern'
    }
  ],
  warnings: []
}
```

**Comment by jcayzac** [comment]
I'm trying to rename some properties, but I can't find a way that works without a lot of boilerplate.

**Comment by jcayzac** [comment]
Never mind, this works:

```ts
const Parser = z.object({
    business_description: z.string().min(1),
    country: z.string().min(1),
    currency_code: z.string().min(1),
    exchange: z.string().min(1),
    industry: z.string().min(1),
    isin: z.string().min(1),
    local_code: z.string().min(1),
    nsin: z.string().min(1),
    pro_name: z.string().min(1),
    sector: z.string().min(1),
    sedol: z.string().min(1),
    session_holidays: z.string()
      .refine((x) => /^(?:\d{8},?)*$/.test(x))
      .transform((x) => x.split(',')),
    short_description: z.string().min(1),
    web_site_url: z.string().min(1),
  })
  .transform((obj) => {
    const {
      business_description: description,
      currency_code: currency,
      pro_name: identifier,
      local_code: localCode,
      session_holidays: holidays,
      short_description: name,
      web_site_url: url,
      ...entries
    } = obj

    return {
      identifier,
      name,
      localCode,
      description,
      url,
      currency,
      holidays,
      ...entries,
    }
  })
```
