### ISSUE TITLE
Nested discriminated unions

### ISSUE THREAD

**Issue by fangel** [colinhacks/zod#1618]
I have a hierarchy of objects, where the first level uses a `type`-property to discriminate, and the second level uses a `subtype`.

An example diagram showing 3 instances on the first level (Foo, Bar & Baz), and then Baz having two subtypes under it (Able & Baker):

```
    [root]
   /  |   \
Foo  Bar   Baz
          /   \
        Able  Baker
```

It's possible to type this in TS with something like
```
type NestedDu = 
   { type: "foo" }
 | { type: "bar" }
 | { type: "baz", subtype: "able" }
 | { type: "baz", subtype: "baker" };
```
(Of course there are more fields on each property, but just keeping it minimal for the ease of understanding)

I tried to construct a Zod-schema using the following
```
const nestedDU = z.discriminatedUnion('type', [
    z.object({
        "type": z.literal("foo")
    }),
    z.object({
        "type": z.literal("bar")
    }),
    z.discriminatedUnion('subtype', [
        z.object({
            "type": z.literal("baz"),
            "subtype": z.literal("able")
        }),
        z.object({
            "type": z.literal("baz"),
            "subtype": z.literal("baker")
        }),
    ]),
]);
```

But this doesn't work, since the outer discriminated union doesn't allow the inner one. 

Is there any way to make this work as-is - or would it need additional work on Zod itself to make it work? I can try to create a PR if needed, but maybe it's already possible and I'm just missing something.

Kind regards
Morten

**Comment by mcky** [comment]
@fangel I raised a similar issue at #1444 which @maxArturo might be addressing in #1589

@maxArturo Morten's description seems to better explain what I was after

**Comment by fangel** [comment]
Sorry, I looked through all the issues to try and find a similar one - but clearly I failed at that. But wonderful that someone else is potentially already looking in to this.

**Comment by maxArturo** [comment]
@mcky @fangel actually we'd need to revise #1589 a bit, since as it stands I wrote the implementation to keep a single `discriminator` key across all nested schemas. At the onset it made sense, but I can also see this use case (different `discriminator` keys in nested `DiscriminatedUnion` schemas) being valid given that TS knows how to distinguish here. 

I'll take a look at updating the PR to satisfy this use case. Thanks!

**Comment by fangel** [comment]
It could also be an option to allow an array of discriminators?

E.g.
```
const nestedDU = z.discriminatedUnion('type', [
    z.object({
        "type": z.literal("foo")
    }),
    z.object({
        "type": z.literal("bar")
    }),
    z.discriminatedUnion(['type', 'subtype'], [
        z.object({
            "type": z.literal("baz"),
            "subtype": z.literal("able")
        }),
        z.object({
            "type": z.literal("baz"),
            "subtype": z.literal("baker")
        }),
    ]),
]);
```

Then the combination of the discriminator-values just needs to be unique... And it nests naively inside another DU with a subset of the discriminators.

**Comment by maxArturo** [comment]
Hey @fangel  thanks for your suggestion! I'd initially be inclined to that, but it really restricts your use of it since you need to know the discriminator values beforehand. For example, I wouldn't be able to export a DU and reuse it across several other definitions, unless I wrap it inside a factory function/closure somehow. 

I _think_ TS definition types should be able to help us here... but at a first pass adding another discriminator type parameter gets weird very fast. Let me think on it a bit and see what we come up with.

**Comment by fangel** [comment]
Wouldn't reuse across other definitions get weird anyway, since you still need to know that the inner DU needs to have a discriminator for the outer DU as well as it's own?

I guess you could do it a factory like e.g.

```
const innerDUFactory = (innerDiscrimnatorName: string, innerDiscriminatorValue: z.AnyType) => z.discriminatedUnion([innerDiscrimnatorName, 'subtype'], [
    z.object({
        [innerDiscrimnatorName]: innerDiscriminatorValue,
        "subtype": z.literal("able")
    }),
    z.object({
        [innerDiscrimnatorName]: innerDiscriminatorValue,
        "subtype": z.literal("baker")
    }),
])
```

My thinking is that the inner-DU always needs to be a valid member of the outer-DU - just that it's _less_ unique because it also needs the inner dimension to be unique.

---

Another option is to do it using some sort of union, where you have the properties for the outer-DU in one half of the union, and then the inner-DU in the other half of the union.

```
const nestedDU = z.discriminatedUnion('type', [
    z.object({
        "type": z.literal("foo")
    }),
    z.object({
        "type": z.literal("bar")
    }),
    z.union([
        z.object({
            "type": z.literal("baz")
        }),
        z.discriminatedUnion('subtype', [
            z.object({
                "subtype": z.literal("able")
            }),
            z.object({
                "subtype": z.literal("baker")
            }),
        ]),
    ]),
]);
```

**Comment by fangel** [comment]
Sorry, the later example should of course be a merge of some sort, not union (it should be a AND, not a OR)

**Comment by maxArturo** [comment]
Hi @fangel! I think your factory solution (or really, any in-situ creation solution) could definitely work. I think it unfortunately breaks up the current API up a bit to ask people to do unions and then discriminated unions (though to be fair there's no API for nested DUs yet :) I just think it would be great to try and make it clean from the outset. 

I think what I was trying to aim at was some sort of solution where we wouldn't have to add extra info, and it would be natural to do the following: 

```ts
  // in base.ts
  export const baseDU = z.discriminatedUnion("baseType", [
    z.object({
      baseType: z.literal("first"),
      specificType: z.literal("main"),
      addenda: z.object({ alternate: z.literal(true) }),
    }),
    z.object({
      baseType: z.literal("second"),
      specificType: z.literal("other"),
    }),
  ]);

  // in specific.ts

  import { baseDU } from "./base";

  const specificDU = z.discriminatedUnion("specificType", [ // no need to define anything else here!
    baseDU,
    z.object({
      specificType: z.literal("additional"),
      extended: z.literal("true"),
    }),
  ]);
```
I'd want the following to happen above
- correct inferred types from TS
- validation that the defined `discriminator` values are recursively enforced down the "DU tree", so that any additional discriminators would be enforced on each `z.object()` as existing keys

The actual non type implementation itself wouldn't be hard at all. We "bubble up" the raw objects of the child DU map's values, and the validation would work above in the following way for `specificDU`: 

- one entry has key: `additional`, value: `z.object()`
- second entry has key: `other`, value: `z.object()`
- third entry has key: `main`, value: `z.object()`

Where I'm currently stuck is I want a clever way to have TS recursively enforce the parent's DU in the child DU: 

```ts
// not the real type but imagine a simplified version
  type DU<
    Discriminator extends String
  > = {
    discriminator: Discriminator;
    duOptions: Array<DU<Discriminators>>; // this doesn't work, want a free unreferenced type variable
  };
```

Note that this is a special case of some sort of type inference like this: [playground](https://www.typescriptlang.org/play?#code/ATAuE8AcFNgYwBYEsA2ATAPAFWNAHqNAHZoDOwAggE5UCG4GpoVSRA5gHwfAC8wA3sADaAa2jhgrYFiFEArgFsARtCoBdNQC5gtIhIC+wAGTAAStDgB7KpgCwAKBAgmLdgBoHTnXs-AOAbl8IGGBIWipiUGxcAmIyShp6RmZWTm4+fl8QRFQ0CKJtajoGS0hQJEsibC5Ax2B9WqCoWFLyyuj8QhJyIqSXVK5eeGR0auAAH1DwyOrGuuDYYgAzazhoNAAFaaIozroYrvj+92l06QO48jD8qNYl1WAADQ4s4AB+AVevHPR8wsSSmUKlUhHtaG5gAA6aGPNQ1L71V7aH6YUEEOhwubZSpMYBKWikaAAeSUACssNBcRlXii-sIEZk6l4QIQmNoAETMOTQdkeJnMsEc2goUiWMBUbm8hH6PnMz7874jPLEbRCBFeRlyuWs0AcgDuCHAUoVWt0llACFUHK5PNlWpAMvVwDUdq8jv5Lt8DQcvisRFxClorC2N201xmQk5lNA7LhQ3xhJJ5OjWPgONAwD1VEqbAAokQVlQ1pttrrcAXVusQzN2WDeWBmpYlsBA8HS2cAPQdltIUikVIHfZSUhyJTDXL5V4J4lkilMVN+3F66wiVL5wvF6s7bTLSslm4YWvo2j1hZNltBohb0BnTVOWkq4SCHUcywiej1wXAdkjiLs+qenUDRAA) . I'll see if I get anywhere shortly with that, otherwise I'll consider a simpler solution like what you suggested!

**Comment by fangel** [comment]
My half-though with the array of discriminators was that it could potentially be something that could be checked with a recursive type-definition 
My thinking would be to recursively loop over the discriminators and the properties and match them up - if we exhaust the properties before the discriminators, then type type should resolve to `never`. I believe this should be achievable with splitting the list up into the head & tail and seeing if the tail is empty.

---

Another option is to look into getting `ZodObject.merge` to accept a discriminate union as the input, because then this would be achievable

```
z.discriminatedUnion('type', [
    z.object({
        "type": z.literal("foo")
    }),
    z.object({
        "type": z.literal("bar")
    }),
    z.object({
        "type": z.literal("baz")
    }).merge(z.discriminatedUnion('subtype', [
        z.object({
            "subtype": z.literal("able")
        }),
        z.object({
            "subtype": z.literal("baker")
        }),
    ])),
]);
``` 

It currently fails because `ZodDiscriminateUnion` isn't assignable to `AnyZodObject`. I guess the semantics are a little weird since then `.merge` would end up basically converting the original object to a union. 

So semantically it's probably nicer to just have DUs nest the way you naively expect them to - i.e. adding the inner DU to the list of objects in the outer DU.

**Comment by maxArturo** [comment]
Hi @fangel thanks so much for your feedback! It really helped me think through the issues at hand and what would work best for this feature. So I came up with something that I think will allow the most flexibility: 

- Create your DUs wherever, then add them in the "parent" DU
- add DUs in-line, and this will work too in both types and implementation

Do you mind taking a look at [this commit](https://github.com/colinhacks/zod/pull/1589/commits/a7f910a018da86decbe645415f62b8048aeb021d) in #1589 and see if it fits your use case? Thanks 🙏

**Comment by fangel** [comment]
Based on the test-schemas that looks _exactly_ like what I envisioned it. On Monday I can see if I can use the PR-code running to test building the schema that I'm envisioning for my use-case.

**Comment by fangel** [comment]
I ran your PR-branch locally, and can confirm that it worked exactly like I'd hope it would. Wonderful work!

**Comment by MrLoh** [comment]
I am trying to achieve a similar nested Discriminated Union and it seems this PR solves that issue as well. Any idea when it might get merged, any way to help? 

This is my use case:

```ts
const ingredientsEventSchema = 

const eventSchema = z.discriminatedUnion('aggregateType', [
  z.discriminatedUnion('type', [
    baseEventSchema.extend({
      aggregateType: z.literal('ingredients'),
      type: z.literal('IMPORTED_INGREDIENT'),
      payload: z.object({ id: z.string(), name: z.string() }),
    }),
    baseEventSchema.extend({
      prevId: z.string().uuid(),
      aggregateType: z.literal('ingredients'),
      type: z.literal('UPDATED_INGREDIENT'),
      payload: z.object({ name: z.string() }),
    }),
  ]),
  z.discriminatedUnion('type', [
    baseEventSchema.extend({
      aggregateType: z.literal('categories'),
      type: z.literal('IMPORTED_CATEGORY'),
      payload: z.object({ id: z.string(), name: z.string() }),
    }),
    baseEventSchema.extend({
      prevId: z.string().uuid(),
      aggregateType: z.literal('categories'),
      type: z.literal('UPDATED_CATEGORY'),
      payload: z.object({ name: z.string() }),
    }),
  ]),
]);
```

**Comment by ian-schu** [comment]
> I am trying to achieve a similar nested Discriminated Union and it seems this PR solves that issue as well. Any idea when it might get merged, any way to help?

+1, I have a similar use case here ✋🏻 and would love to make use of this enhancement.

**Comment by MrLoh** [comment]
not stale

**Comment by leqwasd** [comment]
How about this solutions? Honestly - I have just tried zod for like a couple of hours, but I immediately stumped on this issue.

```typescript
import { z } from "zod";
const nestedDU = z.discriminatedUnion("type", [
  z.object({
    type: z.literal("foo"),
  }),
  z.object({
    type: z.literal("bar"),
  }),
  ...z.discriminatedUnion("subtype", [
    z.object({
      type: z.literal("baz"),
      subtype: z.literal("able"),
    }),
    z.object({
      type: z.literal("baz"),
      subtype: z.literal("baker"),
    }),
  ]).options,
]);

type nestedDUType = z.infer<typeof nestedDU>;
const arr: nestedDUType[] = [
  {
    type: "foo",
  },
  {
    type: "bar",
  },
  {
    type: "baz",
    subtype: "able",
  },
  {
    type: "baz",
    subtype: "able",
  },
];

```
In my actual project where I have TS 4.8, this did not produce the correct results (subtype remained optional). But with TS 5.0.4 it did create correct type, and seemed to work. The key - get the source objects back from discriminatedUnion with `.options` and adding all of them to the original type by spreading them.

**Comment by FunctionDJ** [comment]
not stale 🤯

**Comment by 0xdevalias** [comment]
See also:

- https://github.com/colinhacks/zod/issues/1868

**Comment by andersk** [comment]
@leqwasd While that schema type-checks, it’s rejected by Zod at runtime:

```
file:///tmp/test/node_modules/.pnpm/zod@3.24.1/node_modules/zod/lib/index.mjs:3044
                    throw new Error(`Discriminator property ${String(discriminator)} has duplicate value ${String(value)}`);
                          ^

Error: Discriminator property type has duplicate value baz
    at Object.create [as discriminatedUnion] (file:///tmp/test/node_modules/.pnpm/zod@3.24.1/node_modules/zod/lib/index.mjs:3044:27)
    at file:///tmp/test/test.ts:2:20
    at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)
```

**Comment by leje512** [comment]
I'm also experiencing this issue, and currently unsure on how to build my schema otherwise. I have a nested discriminated Union, that should look like this (not working):

```javascript
z.discriminatedUnion("type", [
  ...z.discriminatedUnion("subtype", [
    z.object({
      type: z.literal("foo"),
      subtype: z.literal("able"),
      value: z.someValidationOnlyAbleGets(),
      foo: z.string()
    }),
    z.object({
      type: z.literal("foo"),
      subtype: z.literal("baker"),
      value: z.someValidationOnlyBakerGets(),
      foo: z.string()
    }),
  ]).options,
  ...z.discriminatedUnion("subtype", [
    z.object({
      type: z.literal("baz"),
      subtype: z.literal("able"),
      value: z.someValidationOnlyAbleGets(),
      baz: z.number()
    }),
    z.object({
      type: z.literal("baz"),
      subtype: z.literal("baker"),
      value: z.someValidationOnlyBakerGets(),
      baz: z.number()
    }),
  ]).options,
]);
```

> @leqwasd While that schema type-checks, it’s rejected by Zod at runtime

Same here

> https://www.ryanschiang.com/zod-nested-discriminated-union

I did try this version with `extend`, but get the same runtime error.

Having this feature would solve the problem! But cause I read its more likely to get deprecated, are there any other ways to build this schema? Maybe without nesting or without discriminated union? Thankful for any tips, I'm still a beginner in zod.

**Comment by djwitcat** [comment]
After some research, I think currently discriminated unions cannot handle this situation.
How about [transform](https://zod.dev/?id=validating-during-transform)? 
I used to facing the same situation several years ago. i need to validate objects with class-validator. 
There is a transform-like function that allows you to use a custom function to determine how to validate an object.
I ended up using this to implement something like.
``` typescript
// Remember to call passthrough, otherwise the fields outside the base schema will be removed
const transformUnion = BaseSchema.passthrough().transform((obj, ctx) => {
  switch (obj.objectType) {
    case "A":
      return A.parse(obj);
    case "B":
      return B.parse(obj);
    // ...
    default:
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: `Invalid object type: ${obj.objectType}`,
      });
      return z.NEVER;
  }
});
```

**Comment by Vincent-HD** [comment]
> After some research, I think currently discriminated unions cannot handle this situation. How about [transform](https://zod.dev/?id=validating-during-transform)? I used to facing the same situation several years ago. i need to validate objects with class-validator. There is a transform-like function that allows you to use a custom function to determine how to validate an object. I ended up using this to implement something like.

Well this seems to work for me, even thought this is not ideal, it should do the job, and the inferred schema seems to be correct on my side, I just slightly edited yours:
```ts
const transformUnion = BaseSchema.passthrough().transform((obj, ctx) => {
  try {
    switch (obj.objectType) {
      case "A":
        return A.parse(obj);
      case "B":
        return B.parse(obj);
      // ...
      // default not useful because it's supposed to be already validated from the BaseSchema
    }
  } catch (e) {
    if (error instanceof z.ZodError) {
      error.errors.forEach((e) => ctx.addIssue(e));
      return z.NEVER;
    }
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      message: 'Invalid object',
    });
    return z.NEVER;
});
```

**Comment by djwitcat** [comment]
> > After some research, I think currently discriminated unions cannot handle this situation. How about [transform](https://zod.dev/?id=validating-during-transform)? I used to facing the same situation several years ago. i need to validate objects with class-validator. There is a transform-like function that allows you to use a custom function to determine how to validate an object. I ended up using this to implement something like.
> 
> Well this seems to work for me, even thought this is not ideal, it should do the job, and the inferred schema seems to be correct on my side, I just slightly edited yours:
> 
> const transformUnion = BaseSchema.passthrough().transform((obj, ctx) => {
>   try {
>     switch (obj.objectType) {
>       case "A":
>         return A.parse(obj);
>       case "B":
>         return B.parse(obj);
>       // ...
>       // default not useful because it's supposed to be already validated from the BaseSchema
>     }
>   } catch (e) {
>     if (error instanceof z.ZodError) {
>       // So that we get every issues from try block validations
>       error.errors.forEach((e) => ctx.addIssue(e));
>       return z.NEVER;
>     }
>     ctx.addIssue({
>       code: z.ZodIssueCode.custom,
>       message: 'Invalid object',
>     });
>     return z.NEVER;
> });

This is a common way to solve similar situations in libraries like zod, because as long as you can define your own functions, you can solve most complex patterns.  
The only problem with this approach is that zod may do redundant work during parsing (because it needs to parse Base schema once first)

**Comment by willisplummer-patreon** [comment]
It seems like zod v4 supports nested discriminated unions, so I guess this can be closed?

From the docs:

<img width="654" height="443" alt="Image" src="https://github.com/user-attachments/assets/d3dc0b5a-ad60-4774-b0cd-a8dcc5fb05a5" />
