### ISSUE TITLE
Error during the parsing of a readonly schema.

### ISSUE THREAD

**Issue by vtgn** [colinhacks/zod#2490]
Hi,

I've been very disappointed by the fact that we can't parse an object with a readonly z.object schema: indeed, it is not secure to not freeze a public complex schema, used by several functionnalities of a software. A developer may do a mistake by modifying the internal data of the schema somewhere, which impacts directly the rest of the software functionnalities. This is not safe coding. :/

The error message during the execution of the Schema.parse method is :
`TypeError: Cannot assign to read only property '_cached' of object '#<O>'

      at O._getCached (../node_modules/@mylib.js:1:44278)
      at O._parse (../node_modules/@mylib.js:1:44518)
      at O._parseSync (../node_modules/@mylib.js:1:22947)
      at O.safeParse (../node_modules/@mylib.js:1:23438)
      at O.parse (../node_modules/@mylib.js:1:23121)`

I suppose the zod library stores a cache inside the z.object schema, which causes the problem. The library should store nothing inside the schema after its creation. If a cache must be used, why not store its contents somewhere inside an internal Map in the zod library inner files, associating a schema to the value(s) to cache associated to it? Plus the advantage you can manage a global cache, with a limited size and/or with a time-limited storage.

zod version: 3.21.4

Regards.

**Comment by JacobWeisenburger** [comment]
Please send a full reproducible code example.

**Comment by vtgn** [comment]
> Please send a full reproducible code example.

Like I said, simply define a Zod schema, put it as argument in the Object.freeze method, define the Zod type of this schema, and parse an object with it :
`
// Create a zod schema and freeze it
const idZodSchema = Object.freeze(z.object({
id: z.number().positive().int().safe()
}));

// Create a zod type
type idZodType = z.infer<typeof idZodSchema>;

// Parse an object with this zod type
const o: idZodType = idZodSchema.parse({ id: 3}); // ======> Error: Cannot assign to read only property '_cached' of object '#<ZodObject>'

console.log(o);
`
