### ISSUE TITLE
Uncatchable `invalid_union` error

### ISSUE THREAD

**Issue by JacobWeisenburger** [colinhacks/zod#2791]
This code should catch and ignore the error, but it does not. There seems to be no way to catch the error.

```ts
try {
    const schema = z.union( [ z.literal( 1 ), z.literal( 2 ) ] )
    const result = schema.safeParse( 3 )
    !result.success && console.log( result.error.issues )
} catch {
    // do nothing
}
```

```
[
  {
    code: "invalid_union",
    unionErrors: [
      159 |     const json = JSON.stringify(obj, null, 2);
160 |     return json.replace(/"([^"]+)":/g, "$1:");
161 | };
162 | class ZodError extends Error {
163 |     constructor(issues) {
164 |         super();
            ^
ZodError: [
  {
    "received": 3,
    "code": "invalid_literal",
    "expected": 1,
    "path": [],
    "message": "Invalid literal value, expected 1"
  }
]
 errors: [
  {
    "received": 3,
    "code": "invalid_literal",
    "expected": 1,
    "path": [],
    "message": "Invalid literal value, expected 1"
  }
]

      at new ZodError (/home/jacob/software/bun-sandbox/node_modules/zod/lib/index.mjs:164:8)
      at /home/jacob/software/bun-sandbox/node_modules/zod/lib/index.mjs:2589:75
      at map (:1:20)
      at _parse (/home/jacob/software/bun-sandbox/node_modules/zod/lib/index.mjs:2589:32)
      at _parseSync (/home/jacob/software/bun-sandbox/node_modules/zod/lib/index.mjs:624:23)
      at safeParse (/home/jacob/software/bun-sandbox/node_modules/zod/lib/index.mjs:654:23)
      at /home/jacob/software/bun-sandbox/src/zod.ts:21:19
, 159 |     const json = JSON.stringify(obj, null, 2);
160 |     return json.replace(/"([^"]+)":/g, "$1:");
161 | };
162 | class ZodError extends Error {
163 |     constructor(issues) {
164 |         super();
            ^
ZodError: [
  {
    "received": 3,
    "code": "invalid_literal",
    "expected": 2,
    "path": [],
    "message": "Invalid literal value, expected 2"
  }
]
 errors: [
  {
    "received": 3,
    "code": "invalid_literal",
    "expected": 2,
    "path": [],
    "message": "Invalid literal value, expected 2"
  }
]

      at new ZodError (/home/jacob/software/bun-sandbox/node_modules/zod/lib/index.mjs:164:8)
      at /home/jacob/software/bun-sandbox/node_modules/zod/lib/index.mjs:2589:75
      at map (:1:20)
      at _parse (/home/jacob/software/bun-sandbox/node_modules/zod/lib/index.mjs:2589:32)
      at _parseSync (/home/jacob/software/bun-sandbox/node_modules/zod/lib/index.mjs:624:23)
      at safeParse (/home/jacob/software/bun-sandbox/node_modules/zod/lib/index.mjs:654:23)
      at /home/jacob/software/bun-sandbox/src/zod.ts:21:19

    ],
    path: [],
    message: "Invalid input"
  }
]
```

```ts
// package.json
{
    "dependencies": {
        "zod": "^3.22.2",
    },
    "devDependencies": {
        "bun-types": "latest"
    },
}
```

**Comment by JacobWeisenburger** [comment]
This seems to only be a problem when using Bun.

When I run this in Node: it doesn't print the error objects full depth by default.
```ts
const schema = z.union( [ z.literal( 1 ), z.literal( 2 ) ] )
const result = schema.safeParse( 3 )
!result.success && console.log( result.error.issues )
// [
//     {
//         code: 'invalid_union',
//         unionErrors: [ [ ZodError ], [ ZodError ] ],
//         path: [],
//         message: 'Invalid input'
//     }
// ]
```

**Comment by JacobWeisenburger** [comment]
This might not be a problem with Zod, but it would be cool if there was a way to fix it in Zod.

I have also put in an issue with Bun that is somewhat related: https://github.com/oven-sh/bun/issues/6039
