### ISSUE TITLE
The .transform method is throwing errors

### ISSUE THREAD

**Issue by FearTheBeard95** [colinhacks/zod#3072]
Hi,

I used the transform method to change some data after parsing. The implementation used to work before but now an error is thrown and i don't understand whats going on as i didn't change anything. here is an example of some code i have using .transform

`export const sheetArrays = z.string().transform(convertToStringsArray);`

with the **convertToStringsArray** function being this

```
const convertToStringsArray = (value: string) => {
  if (!value || value === '') return null;

  const array = value.split('\n');

  return array;
};
```

the error being thrown is this
```
TypeError: effect.transform is not a function
    at ZodEffects._parse (types.js:3375:31)
    at ZodObject._parse (types.js:1957:29)
    at ZodObject._parseSync (types.js:170:25)
    at eval (types.js:1811:23)
    at Array.map (<anonymous>)
    at ZodArray._parse (types.js:1810:34)
    at ZodArray._parseSync (types.js:170:25)
    at ZodArray.safeParse (types.js:207:25)
    at eval (products.ts:722:63)
    at step (products.ts:146:17)
```

**Comment by JacobWeisenburger** [comment]
I ran this code and got no errors:

```ts
const convertToStringsArray = ( value: string ) => {
    if ( !value || value === '' ) return null
    const array = value.split( '\n' )
    return array
}

const sheetArrays = z.string().transform( convertToStringsArray )
```

Please make a repo or codesandbox with a minimal example that reproduces the issue.

**Comment by zaripych** [comment]
Hmm, I was wondering if I should create an issue as well. Here is the minimal reproduction.

```
import { z } from "zod";

const invalidJson = '{"ax: 1}'

console.log(
  z
    .string()
    .transform((val) => JSON.parse(val))
    .safeParse(invalidJson)
);
```

Expected:
```json
{ "success": false, "error": ... }
```

Result:
It throws the exception. "Unexpected end of JSON input".

Basically exceptions are not handled in `transform` or `safeParse` as you would expect them to. 

I've checked the documentation and it doesn't mention anything about handling exceptions in `transform`.

There seem to be similar behaviour for `refine` as well.

zod package version - 3.22.4
