### ISSUE TITLE
Uncaught Error: 

### ISSUE THREAD

**Issue by hussnainAli14** [colinhacks/zod#3147]
[ERROR] service core:user:true-report-v2-development: Uncaught Error: (params) => {

    var _a;
    return new ZodString({
      checks: [],
      typeName: ZodFirstPartyTypeKind.ZodString,
      coerce: (_a = params === null || params === void 0 ? void 0 : params.coerce) !== null && _a
  !== void 0 ? _a : false,
      ...processCreateParams(params)
    });
  } not implemented
    at null.<anonymous> (index.worker.js:75235:9) in y
    at null.<anonymous> (index.worker.js:75251:16) in b
    at null.<anonymous> (index.worker.js:75234:12) in y
    at null.<anonymous> (index.worker.js:75343:87) in getSchemaZod
    at null.<anonymous> (index.worker.js:75179:21)
    at null.<anonymous> (index.worker.js:84264:8)

X [ERROR] MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.

**Comment by JacobWeisenburger** [comment]
Please send a full reproducible code example.

**Comment by JacobWeisenburger** [comment]
You haven't provided enough info for someone to look into this. So I'm going to close this issue for now, and you can post more info if you want to reopen it.
