### ISSUE TITLE
refinement chains unexpectedly violate type safety

### ISSUE THREAD

**Issue by jedwards1211** [colinhacks/zod#3667]
```ts
z.string()
  .refine((s): s is FooBarString => ...)
  .refine((s: FooBarString) => // no TS error, but this can get called with a non-FooBarString
    ...
  )
```

I think the existing behavior is especially unfortunate in cases like this:
```ts
z.string().url().refine(
  // this should be okay, s is definitely a url right?
  s => new URL(s).protocol === 'https:'
).parse('foo')
```

Surprise, nope:
```
Uncaught TypeError: Invalid URL
    at new URL (node:internal/url:775:36)
    at REPL39:3:8
    at Object.refinement (/Users/andy/gh/clarity/node_modules/.pnpm/zod@3.23.8/node_modules/zod/lib/types.js:217:28)
    at executeRefinement (/Users/andy/gh/clarity/node_modules/.pnpm/zod@3.23.8/node_modules/zod/lib/types.js:3178:39)
    at ZodEffects._parse (/Users/andy/gh/clarity/node_modules/.pnpm/zod@3.23.8/node_modules/zod/lib/types.js:3198:17)
    at ZodEffects._parseSync (/Users/andy/gh/clarity/node_modules/.pnpm/zod@3.23.8/node_modules/zod/lib/types.js:146:29)
    at ZodEffects.safeParse (/Users/andy/gh/clarity/node_modules/.pnpm/zod@3.23.8/node_modules/zod/lib/types.js:176:29)
    at ZodEffects.parse (/Users/andy/gh/clarity/node_modules/.pnpm/zod@3.23.8/node_modules/zod/lib/types.js:157:29) {
  code: 'ERR_INVALID_URL',
  input: 'foo'
}
```

I don't think anyone would naively expect Zod to try the refinement on non-URLs, since the behavior of other Zod nodes besides refinements is to abort the chain if one node fails parsing.

**Comment by jedwards1211** [comment]
I think a better compromise would be for builtin refinements like `.min(1).max(128).url()` to all be tried, since the goal is to receive all of those error messages, but for custom refinements to be skipped after an error unless we explicitly opt into it

**Comment by sunnylost** [comment]
Does https://zod.dev/?id=abort-early match your use case?

**Comment by jedwards1211** [comment]
@sunnylost of course I can work around this issue in various ways, including the `fatal` flag, but I am trying to advocate improving the API to where we don't have to work around it, and it's less surprising.

**Comment by benj-dobs** [comment]
I strongly agree that the types should be fixed.

I agree that I would find it more useful to abort-early by default. In particular, having that option within the simpler `refine` API (rather than `superRefine`) would be great, even if it's opt-in. But mainly I want the types to be accurate :)

**Comment by sybereal** [comment]
Not sure if separate issue, but this is especially dangerous if using a refine -> transform -> refine chain. In our case, this was done because the final refinement is a reusable function shared across multiple schemas, while the preceding transform is specific to each schema; its purpose is to transform the disparate inputs into the format expected by the refinement.

The problem is twofold:

- Attaching a transform changes the inferred type, like a refinement with `x is T` return type
- In case of a non-fatal error, transforms are skipped, while refinements are not

This leads to the refinement, which expects the output type of the transform, receiving a completely different type as its input because the transform never ran.

Unfortunately, this means that we now need to go over our entire set of schemas and add `fatal: true` to every refinement or `addIssue()` call, because the default is clearly unsafe.

What's extremely unfortunate is that the docs explicitly advertise this use case as supported:[^docs]

> Transforms and refinements can be interleaved. These will be executed in the order they are declared.

[^docs]: https://zod.dev/?id=relationship-to-refinements

**Comment by jedwards1211** [comment]
Wow @sybereal is right, that is *deeply* flawed behavior:

```
> z.number().refine(x => { console.log('refinement 1'); return x === 1 }).transform(x => { console.log('transform'); return String(x)}).refine(x => { console.log('refinement 2', JSON.stringify(x)); return x === '1' }).safeParse(0)
refinement 1
refinement 2 0
{ success: false, error: [Getter] }
```

@colinhacks
