### ISSUE TITLE
TypeError: Cannot read property '_parseWithInvalidFallback' of undefined

### ISSUE THREAD

**Issue by cakoose** [colinhacks/zod#388]
Zod v3.0.0-alpha.29
Typescript v4.2.4

Short repro:

```ts
import * as z from 'zod';

const geojsonPolygonSchema = z.object({
    type: z.literal('Polygon'),
    coordinates: z.array(z.array(z.tuple([z.number(), z.number()]))),
});

const geojsonMultiPolygonSchema = z.object({
    type: z.literal('MultiPolygon'),
});

const geojsonShapeSchema = z.union([geojsonPolygonSchema, geojsonMultiPolygonSchema]);

const value = {
    "type" : "MultiPolygon",
    "coordinates" : [[[
        [0, 1], [2, 3], [4, 5]
    ]]]
}
console.log(geojsonShapeSchema.safeParse(value));
```

Output:

```
TypeError: Cannot read property '_parseWithInvalidFallback' of undefined
  at Object.function (node_modules/zod/lib/types.js:1340:35)
  at _loop_1 (node_modules/zod/lib/PseudoPromise.js:143:44)
  at PseudoPromise.getValueSync (node_modules/zod/lib/PseudoPromise.js:161:17)
  at node_modules/zod/lib/PseudoPromise.js:102:62
  at Array.map (<anonymous>)
  at Object.function (node_modules/zod/lib/PseudoPromise.js:102:32)
  at _loop_1 (node_modules/zod/lib/PseudoPromise.js:143:44)
  at PseudoPromise.getValueSync (node_modules/zod/lib/PseudoPromise.js:161:17)
  at ZodTuple.ZodType._parseInternal (node_modules/zod/lib/types.js:285:33)
  at ZodTuple.ZodType._parseWithInvalidFallback (node_modules/zod/lib/types.js:154:32)
```

**Comment by colinhacks** [comment]
Good catch! Fixed in alpha.37.
