### ISSUE TITLE
Zod 3 regression "Cannot read property '_parse' of undefined"

### ISSUE THREAD

**Issue by maletor** [colinhacks/zod#528]
I have been trying to get more information, but I cannot isolate this bug.

```
TypeError: Cannot read property '_parse' of undefined
    at ZodObject._parse (/Users/ellis.berner/src/chatbot/node_modules/zod/src/types.ts:1492:22)
    at ZodObject.ZodType._parseSync (/Users/ellis.berner/src/chatbot/node_modules/zod/src/types.ts:102:25)
    at ZodObject.ZodType.safeParse (/Users/ellis.berner/src/chatbot/node_modules/zod/src/types.ts:125:25)
    at ZodObject.ZodType.parse (/Users/ellis.berner/src/chatbot/node_modules/zod/src/types.ts:113:25)
    at Object.queryBotUserInformation (/Users/ellis.berner/src/internal/src/internal.ts:86:69)
```

It appears when trying to _import_ Zod Schema's only, if I copy the Schema definitions over to the same file, the issue is alleviated. It's completely bizarre. 

v3.5.0

My schema, where Token and UserInfo are simple objects, that if I bring into the same file, (not imported) everything works. 

```ts
export const MetaData = z.object({
  token: Token,
  userInfo: UserInfo,
  selectedAccountId: z.string().optional(),
  locale: z.string().optional(),
});
```

What the heck is going on?

**Comment by lilred** [comment]
Can you share what the issue turned out to be?

**Comment by maletor** [comment]
Circular dependency caused an issue where my import was `undefined`. So in the above Token and UserInfo were undefined.

**Comment by vladaman** [comment]
I am experiencing the same issue with following:

```javascript
const IdNumberSchemaNullable = z.union([
    z.number().nonnegative(), // For floating-point numbers and integers
    z.bigint(),  // For big integers (BigInt type)
    z.undefined()
]);

const MyTestSchema =  BaseSchema.extend({
    _t: z.literal('my_test'),
    id_customer: z.IdNumberSchemaNullable, // Nullable Long
```

When id_customer is null it crashes with:
```
TypeError: Cannot read properties of undefined (reading '_parse')
    at ZodObject._parse (file:////node_modules/zod/lib/index.mjs:2525:37)
    at ZodObject._parseSync (file:////node_modules/zod/lib/index.mjs:649:29)
    at ZodDiscriminatedUnion._parse (file:////node_modules/zod/lib/index.mjs:3009:27)
    at ZodDiscriminatedUnion._parseSync (file:////node_modules/zod/lib/index.mjs:649:29)
    at file:////node_modules/zod/lib/index.mjs:2373:29
    at Array.map (<anonymous>)
    at ZodArray._parse (file:////node_modules/zod/lib/index.mjs:2372:38)
    at ZodArray._parseSync (file:////node_modules/zod/lib/index.mjs:649:29)
    at ZodArray.safeParse (file:////node_modules/zod/lib/index.mjs:679:29)
    at ZodArray.parse (file:////node_modules/zod/lib/index.mjs:660:29)
```

Zod version: 3.24.1
