### ISSUE TITLE
Exclude Zod Internals From ZodError Stack Trace

### ISSUE THREAD

**Issue by rubber-duck-software** [colinhacks/zod#538]
I just received a ZodError which reported to the console the following

```
Error: [
  {
    "code": "invalid_arguments",
    "argumentsError": {
      "issues": [
        {
          "code": "too_small",
          "minimum": 1,
          "inclusive": true,
          "type": "array",
          "path": [],
          "message": "Should have at least 1 items"
        }
      ]
    },
    "path": [],
    "message": "Invalid function arguments"
  }
]
    at new ZodError (/Users/USERNAME/PROJECT/node_modules/zod/lib/ZodError.js:75:28)
    at handleArgs (/Users/USERNAME/PROJECT/node_modules/zod/lib/types.js:1786:23)
    at ZodFunction.<anonymous> (/Users/USERNAME/PROJECT/node_modules/zod/lib/types.js:1817:49)
    at step (/Users/USERNAME/PROJECT/node_modules/zod/lib/types.js:59:23)
    at Object.next (/Users/USERNAME/Work/PROJECT/node_modules/zod/lib/types.js:40:53)
    at fulfilled (/Users/USERNAME/PROJECT/node_modules/zod/lib/types.js:31:58)

```

The trouble with an error message like this is that its stack trace is totally uninformative. The reported stack trace is entirely Zod internals with no indication where the problem is in the user code. We should consider filtering zod internals out of the errors stack trace to give the user a more helpful stack trace.

**Comment by rubber-duck-software** [comment]
I see this issue was attempted in 3.7, but it was rolled back in 3.7.1. @colinhacks, can you describe why you had to roll this back?

**Comment by rubber-duck-software** [comment]
This issue is not actually the heart of the problem I am encountering. For people looking for a longer stack trace, I'd recommend setting ```Error.stackTraceLimit = 20``` (or some high number). I think the default is 10.

**Comment by rubber-duck-software** [comment]
See issue https://github.com/colinhacks/zod/issues/572#issue-959549226 for bad stack trace in async function
