### ISSUE TITLE
Bug: TypeError: Cannot read property 'async' of undefined

### ISSUE THREAD

**Issue by extradosages** [colinhacks/zod#665]
Zod v3.9.1.

Error and stack trace:
```
Exception has occurred: TypeError: Cannot read property 'async' of undefined

  at ZodEffects._parse (/mnt/runtime/node_modules/x/node_modules/y/node_modules/zod/src/types.ts:2777:31)
    at ZodObject._parse (/mnt/runtime/node_modules/zod/src/types.ts:1647:22)
    at ZodObject.ZodType._parseSync (/mnt/runtime/node_modules/zod/src/types.ts:148:25)
    at ZodIntersection._parse (/mnt/runtime/node_modules/x/node_modules/zod/src/types.ts:2115:25)
    at /mnt/runtime/node_modules/x/node_modules/zod/src/types.ts:1316:14
    at Array.forEach (<anonymous>)
    at ZodArray._parse (/mnt/runtime/node_modules/x/node_modules/zod/src/types.ts:1313:10)
    at ZodArray.ZodType._parseSync (/mnt/runtime/node_modules/x/node_modules/zod/src/types.ts:148:25)
    at ZodArray.ZodType.safeParse (/mnt/runtime/node_modules/x/node_modules/zod/src/types.ts:181:25)
    at ZodArray.ZodType.parse (/mnt/runtime/node_modules/x/node_modules/zod/src/types.ts:169:25)
 ```
 
 Offending line in source: https://github.com/colinhacks/zod/blob/master/src/types.ts#L3125.
 
 Modifying the compiled output in `lib` from
```
    ZodEffects.prototype._parse = function (ctx, data, parsedType) {
        var isSync = ctx.params.async === false;
```
to 
```
    ZodEffects.prototype._parse = function (ctx, data, parsedType) {
        var isSync = ctx.params?.async === false;
```
fixes the problem.
 
 Seems like just a small oversight somewhere. Anything immediately obvious?

**Comment by extradosages** [comment]
Issue was that a downstream module was using an outdated version of zod.
