### ISSUE TITLE
Zod 3.10.x is broken on node 12

### ISSUE THREAD

**Issue by khaled** [colinhacks/zod#714]
Repo:

```bash
$ docker run -ti --rm --entrypoint sh node:12-slim -c "npm i zod@3.10.1 && node -e \"require('zod').number().parse('5')\""

...

/node_modules/zod/lib/types.js:82
            path: params?.path || [],
                         ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
```

**Comment by sync** [comment]
Null oalescing isn't supported in Node 12.

**Comment by scotttrinh** [comment]
We also claim in the README to support IE11, which we I think we should consider either adding some tooling to enforce, or update the claim.

**Comment by DragosRomaniuc** [comment]
@khaled Did you fix it? I have the same issue
