### ISSUE TITLE
mergeArray in parseUtils can crash if array has empty elements

### ISSUE THREAD

**Issue by nikhilag** [colinhacks/zod#810]
Repro with Zod 3.11.6:-
```
import { z } from "zod";

console.log("Checking schema");
const ZSchema = z.object({
  nos: z.number().nullable().array().optional().nullable()
});

const nos = [];
nos[1] = 10;
const res = ZSchema.safeParse({
  nos
});
```

Error:-
```
TypeError: Cannot read properties of undefined (reading 'status')
    at Function.ParseStatus.mergeArray (https://yb77t.csb.app/node_modules/zod/lib/helpers/parseUtil.js:221:23)

    at ZodArray._parse (https://yb77t.csb.app/node_modules/zod/lib/types.js:1046:40)

    at ZodOptional._parse (https://yb77t.csb.app/node_modules/zod/lib/types.js:2418:36)

    at ZodNullable._parse (https://yb77t.csb.app/node_modules/zod/lib/types.js:2443:36)

    at ZodObject._parse (https://yb77t.csb.app/node_modules/zod/lib/types.js:1158:41)

    at ZodObject.ZodType._parseSync (https://yb77t.csb.app/node_modules/zod/lib/types.js:161:27)

    at ZodObject.ZodType.safeParse (https://yb77t.csb.app/node_modules/zod/lib/types.js:190:27)

    at $csb$eval (https://yb77t.csb.app/src/index.ts:15:19)

    at H (https://codesandbox.io/static/js/sandbox.7e0c76a0e.js:1:99995)

    at K.evaluate (https://codesandbox.io/static/js/sandbox.7e0c76a0e.js:1:112619)

    at ge.evaluateTranspiledModule (https://codesandbox.io/static/js/sandbox.7e0c76a0e.js:1:122966)

    at c (https://codesandbox.io/static/js/sandbox.7e0c76a0e.js:1:112234)

    at loadResources (https://yb77t.csb.app/index.html:3:2)

    at $csb$eval (https://yb77t.csb.app/index.html:9:3)

    at H (https://codesandbox.io/static/js/sandbox.7e0c76a0e.js:1:99995)

    at K.evaluate (https://codesandbox.io/static/js/sandbox.7e0c76a0e.js:1:112619)

    at ge.evaluateTranspiledModule (https://codesandbox.io/static/js/sandbox.7e0c76a0e.js:1:122966)

    at ge.evaluateModule (https://codesandbox.io/static/js/sandbox.7e0c76a0e.js:1:122465)

    at https://codesandbox.io/static/js/sandbox.7e0c76a0e.js:1:314166

    at c (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3629)

    at Generator._invoke (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3382)

    at Generator.forEach.t.<computed> [as next] (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3986)

    at r (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:206)

    at u (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:417)
```

mergeArray in parseUtils:-
![image](https://user-images.githubusercontent.com/54072321/144555986-f9dede2c-d6ed-4e99-88c3-5073d5d9081a.png)

Code sandbox screenshot:-
![image](https://user-images.githubusercontent.com/54072321/144559110-a9b3c82a-7f34-47ca-8562-a05bc44af5d3.png)

**Comment by Eiryyy** [comment]
I faced the same issue.

**Comment by MarcLongJoyride** [comment]
Facing same issue as well.

**Comment by scotttrinh** [comment]
I have validated that this is an issue, but while we're working on a fix, you can use preprocess to remove any `undefined` elements from arrays where you expect this to crop up as a workaround. As far as I know, it's only possible to have a sparse array by specifically constructing it or modifying an array's length property, so it should be possible to know in your application code if this is possible. Obviously this is not a final solution, and perhaps you would want to return an error for this case? If so, I'm not sure that there is a short term workaround other than doing your own runtime check in `preprocess`.

If someone is seeing this at some IO boundary, I would love an example to use as a test case as well!

[CodeSandbox](https://codesandbox.io/s/cool-sanderson-zsho4?file=/src/index.ts)
```ts
// Filter out `undefined` values from a potentially sparse array
const schema = z.object({
  foo: z.preprocess((input) => {
    if (!Array.isArray(input)) {
      return input;
    }

    return input.filter((a) => a !== undefined);
  }, z.array(z.number()))
});
```

**Comment by joshmedeski** [comment]
I had a similar issue in the remix framework. I couldn't import a schema definition from an external module. The schema definition had to all be in the same JavaScript module of the function I was calling the parse method.
