### ISSUE TITLE
Cannot raise issue with custom code and global error map

### ISSUE THREAD

**Issue by brunnerh** [colinhacks/zod#916]
Using `z.setErrorMap` a custom error map can be registered, but the default error map is called before this one and throws an error if the code is not one of the default error codes.

[ZodError.ts](https://github.com/colinhacks/zod/blob/master/src/ZodError.ts)
```js
switch (issue.code) {
    // ...
    default:
      message = _ctx.defaultError;
      util.assertNever(issue); // <--
```

```stacktrace
Error
    at Object.assertNever (node_modules\zod\lib\helpers\util.js:18:15)
    at defaultErrorMap (node_modules\zod\lib\ZodError.js:291:25)
    at makeIssue (node_modules\zod\lib\helpers\parseUtil.js:174:28)
    at addIssueToContext (node_modules\zod\lib\helpers\parseUtil.js:189:39)
    at Object.addIssue (node_modules\zod\lib\types.js:2310:55)
    at Object.notWhiteSpace [as refinement] (out\server.js:5871:13) | <= Custom super refinement here
    at executeRefinement_1 (node_modules\zod\lib\types.js:2326:37)
    at ZodEffects._parse (node_modules\zod\lib\types.js:2346:17)
    at ZodObject._parse (node_modules\zod\lib\types.js:1158:41)
    at ZodObject._parse (node_modules\zod\lib\types.js:1158:41)
```

**Comment by brunnerh** [comment]
I guess this is a misunderstanding of this statement in the documentation?

> Normally refinements always create issues with a `ZodIssueCode.custom` error code, but with `superRefine` you can create any issue of any code.

With "any code" referring to any code known to Zod besides `custom`.

**Comment by andresgutgon** [comment]
Related https://github.com/colinhacks/zod/issues/1043

**Comment by brunnerh** [comment]
It would be nice to know whether this is a bug or not...
