### ISSUE TITLE
Cannot read property '_parse' of undefined

### ISSUE THREAD

**Issue by IRediTOTO** [colinhacks/zod#946]
Hi, I have a Zod object like this

```ts
const zodObj = z.object( { id: string } )
```
then I extend it by
```ts
const extendObj = zodObj.pick( { wrongKey: true, id: true } )
```
when I run 
```ts
extendObj.parse( { id: "xxx" } )
```
I will get error

```
TypeError: Cannot read property '_parse' of undefined
    at s._parse (file:///E:/Job/test/node_modules/zod/lib/index.mjs:1:32502)
    at s.e._parseSync (file:///E:/Job/test/node_modules/zod/lib/index.mjs:1:13917)
    at s.e.safeParse (file:///E:/Job/test/node_modules/zod/lib/index.mjs:1:14474)
    at s.e.parse (file:///E:/Job/test/node_modules/zod/lib/index.mjs:1:14128)
    at Array.eval (webpack-internal:///(api)/./src/pages/api/test.ts:14:104)    
    at loop (file:///E:/Job/test/node_modules/next-connect/dist/index.js:79:47)
    at next (file:///E:/Job/test/node_modules/next-connect/dist/index.js:81:25)
    at AsyncFunction.handle (file:///E:/Job/test/node_modules/next-connect/dist/index.js:83:5)
    at nc (file:///E:/Job/test/node_modules/next-connect/dist/index.js:21:8)
    at Object.apiResolver (E:\Job\test\node_modules\next\dist\server\api-utils\node.js:182:15)
```
This can be fixed by remote `wrongKey` but I think you can fix this to avoid error

**Comment by JacobWeisenburger** [comment]
You need to use [`.extend()`](https://github.com/colinhacks/zod#extend), not [`.pick()`](https://github.com/colinhacks/zod#pickomit).

```ts
const zodObj = z.object( { id: z.string() } )
const extendObj = zodObj.extend( { wrongKey: z.any() } )

console.log( extendObj.parse( { id: 'xxx' } ) ) // { id: 'xxx' }
```
